In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
grouped_stats = df.groupby('Pclass')['Fare'].agg(['mean','median','min','max','std'])
grouped_stats

             mean   median  min       max        std
Pclass
1       84.154687  60.2875  0.0  512.3292  78.380373
2       20.662183  14.2500  0.0   73.5000  13.417399
3       13.675550   8.0500  0.0   69.5500  11.778142

In [4]:
fare_list = df.groupby('Pclass')['Fare'].apply(list)
fare_list

Pclass
1    [71.2833, 53.1, 51.8625, 26.55, 35.5, 263.0, 2...
2    [30.0708, 16.0, 13.0, 26.0, 13.0, 10.5, 21.0, ...
3    [7.25, 7.925, 8.05, 8.4583, 21.075, 11.1333, 1...
Name: Fare, dtype: object

In [6]:
iris = pd.read_csv("iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [11]:
iris['Species'].unique()

<ArrowStringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [12]:
species_group = iris.groupby('Species')

In [13]:
stats = species_group.describe()
stats

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [14]:
for species, data in species_group:
    print("\nSpecies:", species)
    print("Mean:\n", data.mean(numeric_only=True))
    print("Standard Deviation:\n", data.std(numeric_only=True))
    print("Percentiles:\n", data.quantile([0.25, 0.5, 0.75], numeric_only=True))

Species: Iris-setosa
Mean:
 Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64
Standard Deviation:
 Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64
Percentiles:
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

Species: Iris-versicolor
Mean:
 Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64
Standard Deviation:
 Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64
Percentiles:
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

Species: Iris-virginica
Mean:
 Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64
Standard Deviation:
 Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64
Percentiles:
           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3